### PR TITLE
Multiple pages Modified.

### PR DESCRIPTION
**Pull request by theeatch**
modified navbar responsiveness
created reviews for AboutUs
Fixed Testimonials Responsiveness
Created AboutUs
Fixed Products responsiveness

### CODE REVIEW

**Comment by theeatch** [comment]
Need Fix on Contact Component (Responsiveness in Services Page).

**Comment by Crimson-Blade** [comment]
Ok few suggestions:
image
the width of this can be reduced
image
here I'm thinking of putting the search by under the title PRODUCTS

**Comment by Crimson-Blade** [comment]
Finally one design choice we could make is throwing more color into our designs, rn they're too hmm, white ig yea?

For instance here,
image
we could make the right section have colored cards?

**Review by Crimson-Blade — COMMENTED** [review]
Fix menu later

**Review by Crimson-Blade — APPROVED** [review]
lgtmftm

**Pull request merged**
